serverAddr = "43.156.18.225"
serverPort = 7000
transport.dialServerTimeout = 60
loginFailExit = false
auth.method = "token"
auth.token = "88888888"

[log]
level = "debug"
disablePrintColor = true

[[proxies]]
name = "PAD-AUTOSTARTTEST"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5555
